---
- name: Install Nginx
  apt:
    name: nginx
    state: present
  tags: nginx

- name: Configure Nginx
  template:
    src: webbooks.conf.j2
    dest: /etc/nginx/sites-available/webbooks
  notify: restart nginx
  tags: nginx

- name: Enable site
  file:
    src: /etc/nginx/sites-available/webbooks
    dest: /etc/nginx/sites-enabled/webbooks
    state: link
  tags: nginx